// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/login-service/proto/authas/authas.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_login_authas is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/login-service/proto/authas/authas.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_login_authas

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"
import com_HailoOSS_service_login "github.com/HailoOSS/login-service/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Username *string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	// application is for h2 login and namespaces our user pool
	Application *string `protobuf:"bytes,2,opt,name=application" json:"application,omitempty"`
	DeviceType  *string `protobuf:"bytes,3,opt,name=deviceType" json:"deviceType,omitempty"`
	// meta data is optional meta data for h2 logins to attach to the login record, things like IP etc.
	Meta             []*com_HailoOSS_service_login.KeyValue `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *Request) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *Request) GetDeviceType() string {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return ""
}

func (m *Request) GetMeta() []*com_HailoOSS_service_login.KeyValue {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Response struct {
	SessId           *string `protobuf:"bytes,1,req,name=sessId" json:"sessId,omitempty"`
	Token            *string `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetSessId() string {
	if m != nil && m.SessId != nil {
		return *m.SessId
	}
	return ""
}

func (m *Response) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
}
