// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/login-service/proto/readusermulti/readusermulti.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_login_readusermulti is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/login-service/proto/readusermulti/readusermulti.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_login_readusermulti

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"
import com_HailoOSS_service_login_readuser "github.com/HailoOSS/login-service/proto/readuser"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Application      *string  `protobuf:"bytes,1,req,name=application" json:"application,omitempty"`
	Uid              []string `protobuf:"bytes,2,rep,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *Request) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

type Response struct {
	Users            []*com_HailoOSS_service_login_readuser.Response `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte                                          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetUsers() []*com_HailoOSS_service_login_readuser.Response {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
}
