// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/login-service/proto/endpoint.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_login is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/login-service/proto/endpoint.proto

It has these top-level messages:
	Service
	Endpoint
*/
package com_HailoOSS_service_login

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Service struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Role             *string `protobuf:"bytes,2,req,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}

func (m *Service) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Service) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

type Endpoint struct {
	// service + endpoint identify the thing we can call
	Service  *string `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	Endpoint *string `protobuf:"bytes,2,req,name=endpoint" json:"endpoint,omitempty"`
	// services identify what is granted access to this
	Granted          []*Service `protobuf:"bytes,3,rep,name=granted" json:"granted,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}

func (m *Endpoint) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *Endpoint) GetEndpoint() string {
	if m != nil && m.Endpoint != nil {
		return *m.Endpoint
	}
	return ""
}

func (m *Endpoint) GetGranted() []*Service {
	if m != nil {
		return m.Granted
	}
	return nil
}

func init() {
}
