// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/login-service/proto/listsessions/listsessions.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_login_listsessions is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/login-service/proto/listsessions/listsessions.proto

It has these top-level messages:
	Request
	Session
	Response
*/
package com_HailoOSS_service_login_listsessions

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Session struct {
	CreatedTimestamp *int64  `protobuf:"varint,1,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	Mech             *string `protobuf:"bytes,2,opt,name=mech" json:"mech,omitempty"`
	DeviceType       *string `protobuf:"bytes,3,opt,name=deviceType" json:"deviceType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}

func (m *Session) GetCreatedTimestamp() int64 {
	if m != nil && m.CreatedTimestamp != nil {
		return *m.CreatedTimestamp
	}
	return 0
}

func (m *Session) GetMech() string {
	if m != nil && m.Mech != nil {
		return *m.Mech
	}
	return ""
}

func (m *Session) GetDeviceType() string {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return ""
}

type Response struct {
	Sessions         []*Session `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
	Uid              *string    `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *Response) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func init() {
}
